# Generated by Django 4.2.4 on 2023-08-30 15:53
from django.db import migrations


def load_fixture(apps, schema_editor):
    from django.core.management import call_command
    call_command('loaddata', 'fixture_data.json')


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("agency", "0002_auto_20230826_1039"),
    ]

    operations = [
        migrations.RunPython(reverse_func, load_fixture),
    ]
